.TH "H:/sze/Eagle6/ulp/Ulp-Service/editprev-dev-sym-pac.ulp" 3 "Mit Jun 3 2015" "Desy Eagle Bauteil-Datenbank Service Programme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
H:/sze/Eagle6/ulp/Ulp-Service/editprev-dev-sym-pac.ulp \- 
.SH SYNOPSIS
.br
.PP
.SS "Funktionen"

.in +1c
.ti -1c
.RI "\fBif\fP (\fBlibrary\fP) \fBlibrary\fP(L)"
.br
.in -1c
.SS "Variablen"

.in +1c
.ti -1c
.RI "< p >< author > \fBAuthor\fP"
.br
.ti -1c
.RI "string \fBdev\fP []"
.br
.ti -1c
.RI "string \fBsym\fP []"
.br
.ti -1c
.RI "string \fBpac\fP []"
.br
.ti -1c
.RI "string \fBedit\fP = ''"
.br
.ti -1c
.RI "int \fBscount\fP = 0"
.br
.ti -1c
.RI "int \fBdcount\fP = 0"
.br
.ti -1c
.RI "int \fBpcount\fP = 0"
.br
.ti -1c
.RI "int \fBn\fP = 0"
.br
.in -1c
.SH "Dokumentation der Funktionen"
.PP 
.SS "if (\fBlibrary\fP)"

.PP
Definiert in Zeile 17 der Datei editprev-dev-sym-pac\&.ulp\&.
.SH "Variablen-Dokumentation"
.PP 
.SS "<p><author> Author"

.PP
Definiert in Zeile 7 der Datei editprev-dev-sym-pac\&.ulp\&.
.SS "int dcount = 0"

.PP
Definiert in Zeile 13 der Datei editprev-dev-sym-pac\&.ulp\&.
.SS "string dev[]"

.PP
Definiert in Zeile 8 der Datei editprev-dev-sym-pac\&.ulp\&.
.SS "string edit = ''"

.PP
Definiert in Zeile 11 der Datei editprev-dev-sym-pac\&.ulp\&.
.SS "int n = 0"

.PP
Definiert in Zeile 15 der Datei editprev-dev-sym-pac\&.ulp\&.
.SS "string pac[]"

.PP
Definiert in Zeile 10 der Datei editprev-dev-sym-pac\&.ulp\&.
.SS "int pcount = 0"

.PP
Definiert in Zeile 14 der Datei editprev-dev-sym-pac\&.ulp\&.
.SS "int scount = 0"

.PP
Definiert in Zeile 12 der Datei editprev-dev-sym-pac\&.ulp\&.
.SS "string sym[]"

.PP
Definiert in Zeile 9 der Datei editprev-dev-sym-pac\&.ulp\&.
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Desy Eagle Bauteil-Datenbank Service Programme aus dem Quellcode\&.
