.TH "H:/sze/Eagle6/ulp/Ulp-Service/example.c" 3 "Mit Jun 3 2015" "Desy Eagle Bauteil-Datenbank Service Programme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
H:/sze/Eagle6/ulp/Ulp-Service/example.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <systemheader1\&.h>\fP
.br
\fC#include <systemheader2\&.h>\fP
.br
\fC#include <box/header1\&.h>\fP
.br
\fC#include <box/header2\&.h>\fP
.br
\fC#include 'local_header1\&.h'\fP
.br
\fC#include 'local_header2\&.h'\fP
.br

.SS "Klassen"

.in +1c
.ti -1c
.RI "struct \fBBoxStruct_struct\fP"
.br
.RI "\fIUse brief, otherwise the index won't have a brief explanation\&. \fP"
.in -1c
.SS "Makrodefinitionen"

.in +1c
.ti -1c
.RI "#define \fB_BOX_PROTOTYPES_DOXYGEN_H\fP"
.br
.in -1c
.SS "Typdefinitionen"

.in +1c
.ti -1c
.RI "typedef enum \fBBoxEnum_enum\fP \fBBoxEnum\fP"
.br
.RI "\fIUse brief, otherwise the index won't have a brief explanation\&. \fP"
.ti -1c
.RI "typedef struct \fBBoxStruct_struct\fP \fBBoxStruct\fP"
.br
.RI "\fIUse brief, otherwise the index won't have a brief explanation\&. \fP"
.in -1c
.SS "Aufzählungen"

.in +1c
.ti -1c
.RI "enum \fBBoxEnum_enum\fP { \fBBOXENUM_FIRST\fP, \fBBOXENUM_SECOND\fP, \fBBOXENUM_ETC\fP }"
.br
.RI "\fIUse brief, otherwise the index won't have a brief explanation\&. \fP"
.in -1c
.SS "Funktionen"

.in +1c
.ti -1c
.RI "BOXEXPORT \fBBoxStruct\fP * \fBBox_The_Function_Name\fP (BoxParamType1 param1, BoxParamType2 param2)"
.br
.RI "\fIExample showing how to document a function with Doxygen\&. \fP"
.ti -1c
.RI "BOXEXPORT void * \fBBox_The_Second_Function\fP (void)"
.br
.RI "\fIA simple stub function to show how links do work\&. \fP"
.ti -1c
.RI "BOXEXPORT void \fBBox_The_Last_One\fP (void)"
.br
.in -1c
.SH "Makro-Dokumentation"
.PP 
.SS "#define _BOX_PROTOTYPES_DOXYGEN_H"

.PP
Definiert in Zeile 34 der Datei example\&.c\&.
.SH "Dokumentation der benutzerdefinierten Typen"
.PP 
.SS "typedef enum \fBBoxEnum_enum\fP  \fBBoxEnum\fP"

.PP
Use brief, otherwise the index won't have a brief explanation\&. Detailed explanation\&. 
.SS "typedef struct \fBBoxStruct_struct\fP  \fBBoxStruct\fP"

.PP
Use brief, otherwise the index won't have a brief explanation\&. Detailed explanation\&. 
.SH "Dokumentation der Aufzählungstypen"
.PP 
.SS "enum \fBBoxEnum_enum\fP"

.PP
Use brief, otherwise the index won't have a brief explanation\&. Detailed explanation\&. 
.PP
\fBAufzählungswerte\fP
.in +1c
.TP
\fB\fIBOXENUM_FIRST \fP\fP
Some documentation for first\&. 
.TP
\fB\fIBOXENUM_SECOND \fP\fP
Some documentation for second\&. 
.TP
\fB\fIBOXENUM_ETC \fP\fP
Etc\&. 
.PP
Definiert in Zeile 50 der Datei example\&.c\&.
.SH "Dokumentation der Funktionen"
.PP 
.SS "BOXEXPORT \fBBoxStruct\fP* Box_The_Function_Name (BoxParamType1 param1, BoxParamType2 param2)"

.PP
Example showing how to document a function with Doxygen\&. Description of what the function does\&. This part may refer to the parameters of the function, like \fCparam1\fP or \fCparam2\fP\&. A word of code can also be inserted like \fCthis\fP which is equivalent to \fCthis\fP and can be useful to say that the function returns a \fCvoid\fP or an \fCint\fP\&. If you want to have more than one word in typewriter font, then just use <tt>\&. We can also include text verbatim, 
.PP
.nf
like this
.fi
.PP
 Sometimes it is also convenient to include an example of usage: 
.PP
.nf
1 BoxStruct *out = Box_The_Function_Name(param1, param2);
2 printf("something\&.\&.\&.\n");

.fi
.PP
 Or, 
.PP
.nf
1 pyval = python_func(arg1, arg2)
2 print pyval

.fi
.PP
 when the language is not the one used in the current source file (but \fBbe careful\fP as this may be supported only by recent versions of Doxygen)\&. By the way, \fBthis is how you write bold text\fP or, if it is just one word, then you can just do \fBthis\fP\&. 
.PP
\fBParameter:\fP
.RS 4
\fIparam1\fP Description of the first parameter of the function\&. 
.br
\fIparam2\fP The second one, which follows \fCparam1\fP\&. 
.RE
.PP
\fBRückgabe:\fP
.RS 4
Describe what the function returns\&. 
.RE
.PP
\fBSiehe auch:\fP
.RS 4
\fBBox_The_Second_Function\fP 
.PP
\fBBox_The_Last_One\fP 
.PP
http://website/ 
.RE
.PP
\fBZu beachten:\fP
.RS 4
Something to note\&. 
.RE
.PP
\fBWarnung:\fP
.RS 4
Warning\&. 
.RE
.PP

.SS "BOXEXPORT void Box_The_Last_One (void)"
Brief can be omitted\&. If you configure Doxygen with \fCJAVADOC_AUTOBRIEF=YES\fP, then the first Line of the comment is used instead\&. In this function this would be as if 
.PP
.nf
@brief Brief can be omitted. 
.fi
.PP
 was used instead\&. 
.SS "BOXEXPORT void* Box_The_Second_Function (void)"

.PP
A simple stub function to show how links do work\&. Links are generated automatically for webpages (like http://www.google.co.uk) and for structures, like \fBBoxStruct_struct\fP\&. For typedef-ed types use \fBBoxStruct\fP\&. For functions, automatic links are generated when the parenthesis () follow the name of the function, like \fBBox_The_Function_Name()\fP\&. Alternatively, you can use \fBBox_The_Function_Name\fP\&. 
.PP
\fBRückgabe:\fP
.RS 4
\fCNULL\fP is always returned\&. 
.RE
.PP

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Desy Eagle Bauteil-Datenbank Service Programme aus dem Quellcode\&.
