.TH "H:/sze/Eagle6/ulp/Ulp-Service/layer-change.ulp" 3 "Mit Jun 3 2015" "Desy Eagle Bauteil-Datenbank Service Programme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
H:/sze/Eagle6/ulp/Ulp-Service/layer-change.ulp \- 
.SH SYNOPSIS
.br
.PP
.SS "Funktionen"

.in +1c
.ti -1c
.RI "\fBsprintf\fP (\fBtemp\fP,'Grid MM 0\&.635 1 alt mm 0\&.3175 ; \\\fBn\fP')"
.br
.ti -1c
.RI "void \fBChangeTextLayer\fP (UL_TEXT T)"
.br
.ti -1c
.RI "\fBboard\fP (B)"
.br
.ti -1c
.RI "\fBexit\fP (\fBcmd\fP)"
.br
.in -1c
.SS "Variablen"

.in +1c
.ti -1c
.RI "< p > In der Version von Eagle wurden Benutzerdefinierte Layer für SMD \fBBauteile\fP definiert Dies wird ab der Version wieder eingestellt und alle Layer werden auf die Standard Layer und zurückgewandelt< author > \fBAuthor\fP"
.br
.ti -1c
.RI "string \fBcmd\fP = \fBtemp\fP"
.br
.ti -1c
.RI "real \fBdx\fP"
.br
.ti -1c
.RI "real \fBdy\fP"
.br
.in -1c
.SH "Dokumentation der Funktionen"
.PP 
.SS "board (B)"

.PP
Definiert in Zeile 29 der Datei layer-change\&.ulp\&.
.SS "void ChangeTextLayer (UL_TEXT T)"

.PP
Definiert in Zeile 14 der Datei layer-change\&.ulp\&.
.SS "exit (\fBcmd\fP)"

.SS "sprintf (\fBtemp\fP, 'Grid MM 0\&.635 1 alt mm 0\&.3175 ; \\\fBn\fP')"

.SH "Variablen-Dokumentation"
.PP 
.SS "<p> In der Version von Eagle wurden Benutzerdefinierte Layer für SMD \fBBauteile\fP definiert Dies wird ab der Version wieder eingestellt und alle Layer werden auf die Standard Layer und zurückgewandelt<author> Author"

.PP
Definiert in Zeile 8 der Datei layer-change\&.ulp\&.
.SS "cmd = \fBtemp\fP"

.PP
Definiert in Zeile 9 der Datei layer-change\&.ulp\&.
.SS "real dx"

.PP
Definiert in Zeile 10 der Datei layer-change\&.ulp\&.
.SS "real dy"

.PP
Definiert in Zeile 10 der Datei layer-change\&.ulp\&.
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Desy Eagle Bauteil-Datenbank Service Programme aus dem Quellcode\&.
