.TH "H:/sze/Eagle6/ulp/Ulp-Service/main.ulp" 3 "Mit Jun 3 2015" "Desy Eagle Bauteil-Datenbank Service Programme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
H:/sze/Eagle6/ulp/Ulp-Service/main.ulp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Libdesy\&.lib'\fP
.br

.SS "Funktionen"

.in +1c
.ti -1c
.RI "void \fBmain\fP ()"
.br
.in -1c
.SH "Dokumentation der Funktionen"
.PP 
.SS "void main ()"

.PP
Definiert in Zeile 3 der Datei main\&.ulp\&.
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Desy Eagle Bauteil-Datenbank Service Programme aus dem Quellcode\&.
