.TH "H:/sze/Eagle6/ulp/Ulp-Service/nextbib.ulp" 3 "Mit Jun 3 2015" "Desy Eagle Bauteil-Datenbank Service Programme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
H:/sze/Eagle6/ulp/Ulp-Service/nextbib.ulp \- öffnet die nächste Bibliothek und das erste Bauteil in ihr\&.  

.SH SYNOPSIS
.br
.PP
.SS "Funktionen"

.in +1c
.ti -1c
.RI "void \fBmain\fP ()"
.br
.in -1c
.SS "Variablen"

.in +1c
.ti -1c
.RI "int \fBAnzahl_Bibliotheken\fP"
.br
.ti -1c
.RI "string \fBlibsPath\fP []"
.br
.ti -1c
.RI "string \fBcmd\fP"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
öffnet die nächste Bibliothek und das erste Bauteil in ihr\&. 


.PP
\fBAutor:\fP
.RS 4
Jan Scholz 
.RE
.PP

.PP
Definiert in Datei \fBnextbib\&.ulp\fP\&.
.SH "Dokumentation der Funktionen"
.PP 
.SS "void main ()"

.PP
Definiert in Zeile 11 der Datei nextbib\&.ulp\&.
.SH "Variablen-Dokumentation"
.PP 
.SS "int Anzahl_Bibliotheken"

.PP
Definiert in Zeile 8 der Datei nextbib\&.ulp\&.
.SS "string cmd"

.PP
Definiert in Zeile 9 der Datei nextbib\&.ulp\&.
.SS "string libsPath[]"

.PP
Definiert in Zeile 9 der Datei nextbib\&.ulp\&.
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Desy Eagle Bauteil-Datenbank Service Programme aus dem Quellcode\&.
