.TH "H:/sze/Eagle6/ulp/Ulp-Service/readlibs.ulp" 3 "Mit Jun 3 2015" "Desy Eagle Bauteil-Datenbank Service Programme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
H:/sze/Eagle6/ulp/Ulp-Service/readlibs.ulp \- Mit dieser ULP werden die Bauteil Bibliotheken von Eagle eingelesen und in zwei Sortierungen in Dateien abgelegt\&. Einmal nach Package und einmal nach Val\&. Diese Ulp wird einmal pro Woche automatisch ausgeführt\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Libdesy\&.lib'\fP
.br

.SS "Funktionen"

.in +1c
.ti -1c
.RI "string \fBbuildDeviceName\fP (string DSName, string Tech, string Pac)"
.br
.RI "\fIsetzt den Namen des Devices aus den Parametern zusammen, der Platzhalter '*' im namen des Devicesets steht für die Technologie, das '?' steht für das Package\&. Wenn keine Platzhalter vorhanden sind wird der Name nach dem Schema 'DSName + Tech + Pac' erstellt \fP"
.ti -1c
.RI "void \fBmain\fP ()"
.br
.in -1c
.SS "Variablen"

.in +1c
.ti -1c
.RI "< p > Mit dieser ULP werden die Bauteil Bibliotheken von Eagle eingelesen und in zwei Sortierungen in Dateien abgelegt Einmal nach \fBPackage\fP und einmal nach \fBVal\fP Diese Ulp wird einmal pro Woche automatisch ausgeführt</p >< author > \fBAuthor\fP"
.br
.ti -1c
.RI "< p > Mit dieser ULP werden die Bauteil Bibliotheken von Eagle eingelesen und in zwei Sortierungen in Dateien abgelegt Einmal nach \fBPackage\fP und einmal nach \fBVal\fP Diese Ulp wird einmal pro Woche automatisch ausgeführt</p >< author > \fBk\fP = 0"
.br
.ti -1c
.RI "int \fBselector1\fP"
.br
.ti -1c
.RI "int \fBselector2\fP"
.br
.ti -1c
.RI "int \fBbts\fP"
.br
.ti -1c
.RI "int \fBAnzahlLibs\fP"
.br
.ti -1c
.RI "string \fBout\fP"
.br
.ti -1c
.RI "string \fBLIBS\fP []"
.br
.ti -1c
.RI "string \fBrest\fP"
.br
.ti -1c
.RI "string \fBPac_Sort\fP []"
.br
.ti -1c
.RI "string \fBVal_Sort\fP []"
.br
.ti -1c
.RI "string \fBtempstr\fP"
.br
.ti -1c
.RI "string \fBoutAttArr\fP []"
.br
.ti -1c
.RI "string \fBoutElemArr\fP []"
.br
.ti -1c
.RI "string \fBtemp\fP []"
.br
.ti -1c
.RI "string \fBtemp1\fP []"
.br
.ti -1c
.RI "string \fBtemp2\fP []"
.br
.ti -1c
.RI "string \fBtemp3\fP []"
.br
.ti -1c
.RI "string \fBtemp4\fP []"
.br
.ti -1c
.RI "string \fBtemp5\fP []"
.br
.ti -1c
.RI "string \fBHerstellerNummer\fP []"
.br
.ti -1c
.RI "string \fBVal\fP []"
.br
.ti -1c
.RI "string \fBBeschreibung\fP []"
.br
.ti -1c
.RI "string \fBPackage\fP []"
.br
.ti -1c
.RI "string \fBHersteller\fP []"
.br
.ti -1c
.RI "string \fBVorzug\fP []"
.br
.ti -1c
.RI "string \fBOrderbaseNummer\fP []"
.br
.ti -1c
.RI "string \fBDeviceName\fP []"
.br
.ti -1c
.RI "string \fBPrefix\fP []"
.br
.ti -1c
.RI "string \fBDatenblatt1\fP []"
.br
.ti -1c
.RI "string \fBDatenblatt2\fP []"
.br
.ti -1c
.RI "string \fBLIB6_PATH\fP = '//win\&.desy\&.de/group/sze/public/Eagle_6+/lbr'"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
Mit dieser ULP werden die Bauteil Bibliotheken von Eagle eingelesen und in zwei Sortierungen in Dateien abgelegt\&. Einmal nach Package und einmal nach Val\&. Diese Ulp wird einmal pro Woche automatisch ausgeführt\&. 


.PP
\fBAutor:\fP
.RS 4
Jan Scholz 
.RE
.PP

.PP
Definiert in Datei \fBreadlibs\&.ulp\fP\&.
.SH "Dokumentation der Funktionen"
.PP 
.SS "string buildDeviceName (string DSName, string Tech, string Pac)"

.PP
setzt den Namen des Devices aus den Parametern zusammen, der Platzhalter '*' im namen des Devicesets steht für die Technologie, das '?' steht für das Package\&. Wenn keine Platzhalter vorhanden sind wird der Name nach dem Schema 'DSName + Tech + Pac' erstellt 
.PP
\fBParameter:\fP
.RS 4
\fIDSName\fP DeviceSetName 
.br
\fITech\fP Technologie 
.br
\fIPac\fP Package 
.RE
.PP
\fBRückgabe:\fP
.RS 4
DeviceName 
.RE
.PP

.PP
Definiert in Zeile 37 der Datei readlibs\&.ulp\&.
.SS "void main ()"

.PP
Definiert in Zeile 52 der Datei readlibs\&.ulp\&.
.SH "Variablen-Dokumentation"
.PP 
.SS "int AnzahlLibs"

.PP
Definiert in Zeile 18 der Datei readlibs\&.ulp\&.
.SS "<p> Mit dieser ULP werden die Bauteil Bibliotheken von Eagle eingelesen und in zwei Sortierungen in Dateien abgelegt Einmal nach \fBPackage\fP und einmal nach \fBVal\fP Diese Ulp wird einmal pro Woche automatisch ausgeführt</p><author> Author"

.PP
Definiert in Zeile 16 der Datei readlibs\&.ulp\&.
.SS "string Beschreibung[]"

.PP
Definiert in Zeile 23 der Datei readlibs\&.ulp\&.
.SS "int bts"

.PP
Definiert in Zeile 17 der Datei readlibs\&.ulp\&.
.SS "string Datenblatt1[]"

.PP
Definiert in Zeile 23 der Datei readlibs\&.ulp\&.
.SS "string Datenblatt2[]"

.PP
Definiert in Zeile 23 der Datei readlibs\&.ulp\&.
.SS "string DeviceName[]"

.PP
Definiert in Zeile 23 der Datei readlibs\&.ulp\&.
.SS "string Hersteller[]"

.PP
Definiert in Zeile 23 der Datei readlibs\&.ulp\&.
.SS "string HerstellerNummer[]"

.PP
Definiert in Zeile 23 der Datei readlibs\&.ulp\&.
.SS "<p> Mit dieser ULP werden die Bauteil Bibliotheken von Eagle eingelesen und in zwei Sortierungen in Dateien abgelegt Einmal nach \fBPackage\fP und einmal nach \fBVal\fP Diese Ulp wird einmal pro Woche automatisch ausgeführt</p><author> k = 0"

.PP
Definiert in Zeile 16 der Datei readlibs\&.ulp\&.
.SS "string LIB6_PATH = '//win\&.desy\&.de/group/sze/public/Eagle_6+/lbr'"

.PP
Definiert in Zeile 24 der Datei readlibs\&.ulp\&.
.SS "string LIBS[]"

.PP
Definiert in Zeile 19 der Datei readlibs\&.ulp\&.
.SS "string OrderbaseNummer[]"

.PP
Definiert in Zeile 23 der Datei readlibs\&.ulp\&.
.SS "string out"

.PP
Definiert in Zeile 19 der Datei readlibs\&.ulp\&.
.SS "string outAttArr[]"

.PP
Definiert in Zeile 22 der Datei readlibs\&.ulp\&.
.SS "string outElemArr[]"

.PP
Definiert in Zeile 22 der Datei readlibs\&.ulp\&.
.SS "string Pac_Sort[]"

.PP
Definiert in Zeile 20 der Datei readlibs\&.ulp\&.
.SS "string Package[]"

.PP
Definiert in Zeile 23 der Datei readlibs\&.ulp\&.
.SS "string Prefix[]"

.PP
Definiert in Zeile 23 der Datei readlibs\&.ulp\&.
.SS "string rest"

.PP
Definiert in Zeile 19 der Datei readlibs\&.ulp\&.
.SS "int selector1"

.PP
Definiert in Zeile 17 der Datei readlibs\&.ulp\&.
.SS "int selector2"

.PP
Definiert in Zeile 17 der Datei readlibs\&.ulp\&.
.SS "string temp[]"

.PP
Definiert in Zeile 22 der Datei readlibs\&.ulp\&.
.SS "string temp1[]"

.PP
Definiert in Zeile 22 der Datei readlibs\&.ulp\&.
.SS "string temp2[]"

.PP
Definiert in Zeile 22 der Datei readlibs\&.ulp\&.
.SS "string temp3[]"

.PP
Definiert in Zeile 22 der Datei readlibs\&.ulp\&.
.SS "string temp4[]"

.PP
Definiert in Zeile 22 der Datei readlibs\&.ulp\&.
.SS "string temp5[]"

.PP
Definiert in Zeile 22 der Datei readlibs\&.ulp\&.
.SS "string tempstr"

.PP
Definiert in Zeile 21 der Datei readlibs\&.ulp\&.
.SS "string Val[]"

.PP
Definiert in Zeile 23 der Datei readlibs\&.ulp\&.
.SS "string Val_Sort[]"

.PP
Definiert in Zeile 20 der Datei readlibs\&.ulp\&.
.SS "string Vorzug[]"

.PP
Definiert in Zeile 23 der Datei readlibs\&.ulp\&.
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Desy Eagle Bauteil-Datenbank Service Programme aus dem Quellcode\&.
