.TH "H:/sze/Eagle6/ulp/Ulp-Service/suche.ulp" 3 "Mit Jun 3 2015" "Desy Eagle Bauteil-Datenbank Service Programme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
H:/sze/Eagle6/ulp/Ulp-Service/suche.ulp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Libdesy\&.lib'\fP
.br

.SS "Funktionen"

.in +1c
.ti -1c
.RI "\fBfileread\fP (\fBBauteile\fP,'C:/Users/scholzj/Desktop/\fBBauteile\fP')"
.br
.ti -1c
.RI "\fBdlgDialog\fP ('')"
.br
.in -1c
.SS "Variablen"

.in +1c
.ti -1c
.RI "string \fBBauteile\fP []"
.br
.ti -1c
.RI "string \fBsuchtext\fP"
.br
.ti -1c
.RI "string \fBtable\fP []"
.br
.ti -1c
.RI "string \fBtreffer\fP"
.br
.ti -1c
.RI "int \fBselected\fP"
.br
.ti -1c
.RI "int \fBanfang\fP"
.br
.ti -1c
.RI "int \fBlaenge\fP"
.br
.ti -1c
.RI "int \fBcnt\fP"
.br
.in -1c
.SH "Dokumentation der Funktionen"
.PP 
.SS "dlgDialog ('')"

.PP
Definiert in Zeile 8 der Datei suche\&.ulp\&.
.SS "fileread (\fBBauteile\fP, 'C:/Users/scholzj/Desktop/\fBBauteile\fP')"

.SH "Variablen-Dokumentation"
.PP 
.SS "int anfang"

.PP
Definiert in Zeile 6 der Datei suche\&.ulp\&.
.SS "string Bauteile[]"

.PP
Definiert in Zeile 2 der Datei suche\&.ulp\&.
.SS "int cnt"

.PP
Definiert in Zeile 6 der Datei suche\&.ulp\&.
.SS "int laenge"

.PP
Definiert in Zeile 6 der Datei suche\&.ulp\&.
.SS "int selected"

.PP
Definiert in Zeile 5 der Datei suche\&.ulp\&.
.SS "string suchtext"

.PP
Definiert in Zeile 3 der Datei suche\&.ulp\&.
.SS "string table[]"

.PP
Definiert in Zeile 3 der Datei suche\&.ulp\&.
.SS "string treffer"

.PP
Definiert in Zeile 4 der Datei suche\&.ulp\&.
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Desy Eagle Bauteil-Datenbank Service Programme aus dem Quellcode\&.
