.TH "H:/sze/Eagle6/ulp/Ulp-Service/text.ulp" 3 "Mit Jun 3 2015" "Desy Eagle Bauteil-Datenbank Service Programme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
H:/sze/Eagle6/ulp/Ulp-Service/text.ulp \- Value und Name von Packages werden auf die richtigen Layer gesetzt und die Schrifftgröße wird angepasst\&.  

.SH SYNOPSIS
.br
.PP
.SS "Funktionen"

.in +1c
.ti -1c
.RI "string \fBint2str\fP (int number)"
.br
.ti -1c
.RI "void \fBChangeTextLayer\fP (UL_TEXT T)"
.br
.ti -1c
.RI "void \fBDoPackage\fP (UL_PACKAGE P)"
.br
.ti -1c
.RI "void \fBDoSymbol\fP (UL_SYMBOL S)"
.br
.ti -1c
.RI "\fBif\fP (\fBlibrary\fP)"
.br
.ti -1c
.RI "\fBexit\fP (0)"
.br
.in -1c
.SS "Variablen"

.in +1c
.ti -1c
.RI "string \fBtemp\fP"
.br
.ti -1c
.RI "string \fBcmd\fP"
.br
.ti -1c
.RI "real \fBdx\fP"
.br
.ti -1c
.RI "real \fBdy\fP"
.br
.ti -1c
.RI "\fBelse\fP"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
Value und Name von Packages werden auf die richtigen Layer gesetzt und die Schrifftgröße wird angepasst\&. 


.PP
\fBAutor:\fP
.RS 4
Jan Scholz 
.RE
.PP

.PP
Definiert in Datei \fBtext\&.ulp\fP\&.
.SH "Dokumentation der Funktionen"
.PP 
.SS "void ChangeTextLayer (UL_TEXT T)"

.PP
Definiert in Zeile 17 der Datei text\&.ulp\&.
.SS "void DoPackage (UL_PACKAGE P)"

.PP
Definiert in Zeile 32 der Datei text\&.ulp\&.
.SS "void DoSymbol (UL_SYMBOL S)"

.PP
Definiert in Zeile 70 der Datei text\&.ulp\&.
.SS "exit (0)"

.SS "if (\fBlibrary\fP)"

.PP
Definiert in Zeile 96 der Datei text\&.ulp\&.
.SS "string int2str (int number)"

.PP
Definiert in Zeile 11 der Datei text\&.ulp\&.
.SH "Variablen-Dokumentation"
.PP 
.SS "string cmd"

.PP
Definiert in Zeile 8 der Datei text\&.ulp\&.
.SS "real dx"

.PP
Definiert in Zeile 9 der Datei text\&.ulp\&.
.SS "real dy"

.PP
Definiert in Zeile 9 der Datei text\&.ulp\&.
.SS "else"
\fBInitialisierung:\fP
.PP
.nf
{
   dlgMessageBox("\n*** Start this ULP in a Library ***\n")
.fi
.PP
Definiert in Zeile 120 der Datei text\&.ulp\&.
.SS "string temp"

.PP
Definiert in Zeile 8 der Datei text\&.ulp\&.
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für Desy Eagle Bauteil-Datenbank Service Programme aus dem Quellcode\&.
